service: dynamodb
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

resources:
  Resources:
    UserDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: account_number
            AttributeType: S
        KeySchema:
          -
            AttributeName: account_number
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: user
