version: 0.1
phases:
  install:
    commands:
      - cd lambdas/user
      - npm install
  pre_build:
    commands:
      - npm run lint
      - npm run test
  build:
    commands:
      - npm run deploy
