service: user-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-bundle
